services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wordpress-container
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DEBUG: 1
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - wordpress-data:/var/www/html
      - wordpress-uploads:/var/www/html/wp-content/uploads
      - wordpress-cache:/var/www/html/wp-content/cache
      - "./meu-plugin:/var/www/html/wp-content/plugins/meu-plugin"
      - "./meu-tema:/var/www/html/wp-content/themes/meu-tema"
    networks:
      - wordpress-network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - wordpress-network

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wpuser", "-pwppass"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wordpress-network

  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8081:8080"
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  wordpress-data:
    driver: local
  wordpress-uploads:
    driver: local
  wordpress-cache:
    driver: local
  mysql-data:
    driver: local
