services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    restart: unless-stopped
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - wordpress-data:/var/www/html
      - "./meu-plugin:/var/www/html/wp-content/plugins/meu-plugin"
      - "./meu-tema:/var/www/html/wp-content/themes/meu-tema"
    networks:
      - wordpress-network

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${MYSQL_MEMORY_LIMIT}
        reservations:
          memory: ${MYSQL_MEMORY_RESERVATION}
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
    networks:
      - wordpress-network

  adminer:
    image: adminer
    container_name: adminer-container
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  wordpress-data:
    driver: local
  mysql-data:
    driver: local
    name: wordpress_mysql_data
    labels:
      com.mysql.description: "MySQL Data Volume"
      com.mysql.environment: "development"
  mysql-logs:
    driver: local
    name: wordpress_mysql_logs
    labels:
      com.mysql.description: "MySQL Logs Volume"
      com.mysql.environment: "development"